version: '3'

services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - ./data/wordpress:/var/www/html
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    networks:
      - inception_net
    restart: always

  wordpress:
    build: ./requirements/wordpress
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
    volumes:
      - ./data/wordpress:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception_net
    restart: always

  mariadb:
    build: ./requirements/mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./data/database:/var/lib/mysql
    networks:
      - inception_net
    restart: always

networks:
  inception_net:
