
services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    image: mariadb:af
    expose:
      - "3306"
    env_file:
      - /home/antoda-s/secrets/.env
    restart: 
      on-failure:5
    networks:
      - inception
    volumes:
      - dbvol:/var/lib/mysql
      - /home/antoda-s/secrets/secrets.enc:/run/secrets/secrets.enc:ro
    secrets:
      - secret_key
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  wordpress:
    build: ./requirements/bonus/wordpress
    container_name: wordpress
    image: wordpress:af
    expose:
      - "9000"
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - /home/antoda-s/secrets/.env
    restart: 
      on-failure:5
    networks:
      - inception
    volumes:
      - wpvol:/var/www/html/wordpress
      - /home/antoda-s/secrets/secrets.enc:/run/secrets/secrets.enc:ro
    secrets:
      - secret_key
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
  
  website:
    build: ./requirements/bonus/website
    container_name: website
    image: website:af
    volumes:
      - wsvol:/var/www/html
    networks:
      - inception
    restart: on-failure:5

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    image: nginx:af
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - wordpress
      - website
    env_file:
      - /home/antoda-s/secrets/.env
    restart: 
      on-failure:5
    volumes:
      - wpvol:/var/www/html/wordpress
      - wsvol:/var/www/html/website
    networks:
      - inception
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  ftp:
    build: ./requirements/bonus/ftp
    container_name: ftp
    image: ftp:af
    expose:
      - "21"
      - "10000-10100"
    ports:
      - "21:21"
      - "10000-10100:10000-10100"
    depends_on:
      - wordpress
    env_file:
      - /home/antoda-s/secrets/.env
    restart: 
      on-failure:5
    volumes:
      - wpvol:/var/ftp/users/ftpuser/wordpress
      - /home/antoda-s/secrets/secrets.enc:/run/secrets/secrets.enc:ro
    secrets:
      - secret_key
    networks:
      - inception
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
  
  redis:
    build: requirements/bonus/redis
    container_name: redis
    image: redis:af
    networks:
      - inception
    restart:
      on-failure:5
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 3
      timeout: 3s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
  
  adminer:
    build: requirements/bonus/adminer
    container_name: adminer
    image: adminer:af
    ports:
      - target: 8080
        published: 8080
    networks:
      - inception
    restart:
      on-failure:5
    mem_limit: 512m
 
  rsync:
    build: requirements/bonus/rsync
    container_name: rsync
    image: rsync:af
    env_file:
      - /home/antoda-s/secrets/.env
    volumes:
      - wpvol:/var/www/html
      - rsync:/home/backup/
    networks:
      - inception
    restart:
      on-failure:5

secrets:
  secret_key:
    file: /home/antoda-s/secrets/secrets_vault/decryptkey.txt

networks:
  inception:
    name: inception
    driver: bridge

volumes: 
  dbvol:
    name: dbvol
    driver: local
    driver_opts:
      type: none
      device: /home/antoda-s/data/db
      o: bind
  wpvol:
    name: wpvol
    driver: local
    driver_opts:
      type: none
      device: /home/antoda-s/data/wp
      o: bind
  rsync:
    name: rsync
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: /home/antoda-s/data/backup
  wsvol:
    name: wsvol
    driver: local
    driver_opts:
      type: none
      device: /home/antoda-s/ws
      o: bind