services:
  mariadb:
    container_name: mariadb
    hostname: mariadb
    expose:
      - "3306"
    volumes:
      - data_db:/var/lib/mysql  # Persistent storage
    networks:
      - inception
    build: ./requirements/mariadb
    restart: always
    env_file: .env  # Loads environment variables from .env file

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    expose:
      -  "9000"
    volumes:
      - data_wp:/var/www/html
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    networks:
      - inception
    restart: always
    env_file: .env  # Loads environment variables from .env file

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    environment:
      - WP_DB_HOST=mariadb
      - WP_DB_USER=${MYSQL_USER}
      - WP_DB_PASSWORD=${MYSQL_PASSWORD}
      - WP_DB_NAME=${MYSQL_DATABASE}
      - WP_DB_ADMIN=${MYSQL_ADMIN_USER}
      - WP_DB_ADMIN_PASS=${MYSQL_ADMIN_PASSWORD}
    ports:
      - "443:443"
    expose:
      - "3306"
      - "9000"
    volumes:
      - data_wp:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception
    restart: always
    env_file: .env  # Loads environment variables from .env file

networks:
  inception:

volumes:
  data_db:
    driver: local
    driver_opts:
      type: none
      device: /home/antoda-s/data/db
      o: bind
  data_wp:
    driver: local
    driver_opts:
      type: none
      device: /home/antoda-s/data/wp
      o: bind
  
#********************************************


