services:
  mariadb:
    container_name: mariadb
    hostname: mariadb
    expose:
      - "3306"
    volumes:
      - data_db:/var/lib/mysql
    networks:
      - inception
    build: ./requirements/mariadb
    restart: always
    env_file: .env

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    expose:
      - "9000"
    volumes:
      - data_wp:/var/www/html
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    networks:
      - inception
    depends_on:
      - wordpress
    restart: always
    env_file: .env

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_ADMIN: ${MYSQL_ADMIN_USER}
      WORDPRESS_DB_ADMIN_PASS: ${MYSQL_ADMIN_PASSWORD}
    expose:
      - "9000"
    volumes:
      - data_wp:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception
    restart: always
    env_file: .env

networks:
  inception:

volumes:
  data_db:
    driver: local
    driver_opts:
      type: none
      device: /home/antoda-s/data/db
      o: bind
  data_wp:
    driver: local
    driver_opts:
      type: none
      device: /home/antoda-s/data/wp
      o: bind
  
#********************************************


