
services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    image: mariadb:42
    expose:
      - "3306"
    env_file:
      - /home/antoda-s/secrets/.env
    restart:
      on-failure:5
    networks:
      - inception
    volumes:
      - dbvol:/var/lib/mysql
      - /home/antoda-s/secrets/secrets.enc:/run/secrets/secrets.enc:ro
      # - ../secrets/secrets.enc:/run/secrets/secrets.enc:ro
    secrets:
      - secret_key
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress:42
    expose:
      - "9000"
    depends_on:
      mariadb:
        condition: service_healthy
    env_file:
      - /home/antoda-s/secrets/.env
    restart:
      on-failure:5
    networks:
      - inception
    volumes:
      - wpvol:/var/www/html/wordpress
      - /home/antoda-s/secrets/secrets.enc:/run/secrets/secrets.enc:ro
    secrets:
      - secret_key
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    image: nginx:42
    ports:
      - "443:443"
    depends_on:
      - wordpress
    env_file:
      - /home/antoda-s/secrets/.env
    restart:
      on-failure:5
    volumes:
      - wpvol:/var/www/html/wordpress
    networks:
      - inception
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

secrets:
  secrets_enc:
    file: /home/antoda-s/secrets/secrets.enc
  secret_key:
    file: /home/antoda-s/secrets/secrets_vault/decryptkey.txt

networks:
  inception:
    name: inception
    driver: bridge

volumes: 
  dbvol:
    name: dbvol
    driver: local
    driver_opts:
      type: none
      device: /home/antoda-s/data/db
      o: bind
  wpvol:
    name: wpvol
    driver: local
    driver_opts:
      type: none
      device: /home/antoda-s/data/wp
      o: bind
