services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb:42
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_DATABASE_FILE: /run/secrets/db_name
    secrets:
      - db_password
      - db_root_password
      - db_name
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
      - ../secrets/db_root_password.txt:/run/secrets/db_root_password:ro
      - ../secrets/db_password.txt:/run/secrets/db_password:ro
      - ../secrets/db_name.txt:/run/secrets/db_name:ro
    networks:
      - project_network
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress:42
    env_file:
      - .env
    environment:
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
      WORDPRESS_DB_HOST_FILE: /run/secrets/db_host
      WORDPRESS_DB_NAME_FILE: /run/secrets/db_name
      WORDPRESS_ADMIN_PASSWORD_FILE: /run/secrets/wp_admin_password
      WORDPRESS_USER_PASSWORD_FILE: /run/secrets/wp_user_password
    ports:
      - 9000:9000
    depends_on:
      - mariadb
    volumes:
      - wordpress-data:/var/www/html/wordpress
      - ../secrets/db_password.txt:/run/secrets/db_password:ro
      - ../secrets/db_host.txt:/run/secrets/db_host:ro
      - ../secrets/db_name.txt:/run/secrets/db_name:ro
      - ../secrets/wp_admin_password.txt:/run/secrets/wp_admin_password:ro
      - ../secrets/wp_user_password.txt:/run/secrets/wp_user_password:ro
    networks:
      - project_network
    restart: always

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:42
    ports:
      - 443:443
    depends_on:
      - wordpress
    volumes:
      - wordpress-data:/var/www/html/wordpress
    networks:
      - project_network
    restart: unless-stopped
    # restart: always

volumes:
  db-data:
    name: mariadb_volume
    driver: local
    driver_opts:
      type: none
      device: /home/anton/data/db
      o: bind
  wordpress-data:
    name: wordpress_volume
    driver: local
    driver_opts:
      type: none
      device: /home/anton/data/wp
      o: bind

networks:
  project_network:
    name: inception_network
    driver: bridge

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_host:
    file: ../secrets/db_host.txt
  db_name:
    file: ../secrets/db_name.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
