services:
  mariadb:
    container_name: mariadb
    hostname: mariadb
    ports:
      - "3306:3306"
    volumes:
      - db_datas:/var/lib/mysql  # Persistent storage
    networks:
      - inception
    build: ./requirements/mariadb
    restart: always
    env_file: .env  # Loads environment variables from .env file

networks:
  inception:

volumes:
  db_datas:
    driver: local
    driver_opts:
      type: none
      device: /home/antoda-s/data/db
      o: bind
