
services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    image: mariadb:42
    expose:
      - "3306"
    env_file:
      - ../.env
    restart: always
    networks:
      - inception
    volumes:
      - dbvol:/var/lib/mysql
      - ../secrets/secrets.enc:/run/secrets/secrets.enc:ro
    secrets:
      - secret_key
#    healthcheck:
#      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
#      interval: 10s
#      timeout: 5s
#      retries: 5
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress:42
    expose:
      - "9000"
    depends_on:
      - mariadb
#        condition: service_healthy
    env_file:
      - ../.env
    restart: always
    networks:
      - inception
    volumes:
      - wpvol:/var/www/html/wordpress
      - ../secrets/secrets.enc:/run/secrets/secrets.enc:ro
    secrets:
      - secret_key
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:9000"]
#      interval: 1m
#      timeout: 20s
#      retries: 5
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    image: nginx:42
    ports:
      - "443:443"
    depends_on:
      - wordpress
#        condition: service_healthy
    env_file:
      - ../.env
    restart: always
    volumes:
      - wpvol:/var/www/html/wordpress
    networks:
      - inception
#    healthcheck:
#      test: ["CMD", "curl", "-f", "https://localhost"]
#      interval: 30s
#      timeout: 10s
#      retries: 5
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  ftp:
    build: ./requirements/bonus/ftp
    container_name: ftp
    image: ftp:42
    expose:
      - "21"
      - "10000-10100"
    ports:
      - "21:21"
      - "10000-10100:10000-10100"
    depends_on:
      - wordpress
#        condition: service_healthy
    env_file:
      - ../.env
    restart: always
    volumes:
      - wpvol:/var/ftp/users/ftpuser/wordpress
      - ../secrets/secrets.enc:/run/secrets/secrets.enc:ro
    secrets:
      - secret_key
    networks:
      - inception
#    healthcheck:
#      test: ["CMD", "curl", "-f", "ftp://localhost"]
#      interval: 30s
#      timeout: 10s
#      retries: 5
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

secrets:
  secrets_enc:
    file: ../secrets/secrets.enc
  secret_key:
    file: ../secrets/secrets_vault/decryptkey.txt

networks:
  inception:
    name: inception
    driver: bridge

volumes: 
  dbvol:
    name: dbvol
    driver: local
    driver_opts:
      type: none
      device: /home/antoda-s/data/db
      o: bind
  wpvol:
    name: wpvol
    driver: local
    driver_opts:
      type: none
      device: /home/antoda-s/data/wp
      o: bind
