
services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    image: mariadb:42
    expose:
      - "3306"
    env_file:
      - .env
    restart: on-failure
    networks:
      - inception
    volumes:
      - dbvol:/var/lib/mysql

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress:42
    expose:
      - "9000"
    depends_on:
      - mariadb
    env_file:
      - .env
    restart: on-failure
    networks:
      - inception
    volumes:
      - wpvol:/var/www/html/wordpress

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    image: nginx:42
    ports:
      - "443:443"
    depends_on:
      - wordpress
    env_file:
      - .env
    restart: on-failure
    networks:
      - inception
    volumes:
      - wpvol:/var/www/html/wordpress

networks:
  inception:
    name: inception
    driver: bridge

volumes: 
  dbvol:
    name: dbvol
    driver: local
    driver_opts:
      type: none
      device: /home/antoda-s/data/db
      o: bind
  wpvol:
    name: wpvol
    driver: local
    driver_opts:
      type: none
      device: /home/antoda-s/data/wp
      o: bind