services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    image: mariadb:42
    expose:
      - "3306"
    env_file:
      - ../.env
    restart: always
    networks:
      - inception
    volumes:
      - dbvol:/var/lib/mysql
      - ../secrets/secrets.enc:/run/secrets/secrets.enc:ro
    secrets:
      - secret_key

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress:42
    expose:
      - "9000"
    depends_on:
      - mariadb
    env_file:
      - ../.env
    restart: on-failure
    networks:
      - inception
    volumes:
      - wpvol:/var/www/html/wordpress
      - ../secrets/secrets.enc:/run/secrets/secrets.enc:ro
    secrets:
      - secret_key
  
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    image: nginx:42
    ports:
      - "443:443"
    depends_on:
      - wordpress
    env_file:
      - ../.env
    restart: on-failure
    networks:
      - inception
    volumes:
      - wpvol:/var/www/html/wordpress

  ftp:
    build: ./requirements/ftp
    container_name: ftp
    image: ftp:42
    expose:
      - "21"
      - "10000-10100"
    ports:
      - "21:21"
      - "10000-10100:10000-10100"
    depends_on:
      - wordpress
    networks:
      - inception
    volumes:
      - wpvol:/var/ftp/users
      - ../secrets/secrets.enc:/run/secrets/secrets.enc:ro
    secrets:
      - secret_key
    restart: always

secrets:
  secrets_enc:
    file: ../secrets/secrets.enc
  secret_key:
    file: ../secrets/decryptkey.txt

networks:
  inception:
    name: inception
    driver: bridge

volumes: 
  dbvol:
    name: dbvol
    driver: local
    driver_opts:
      type: none
      device: /home/antoda-s/data/db
      o: bind
  wpvol:
    name: wpvol
    driver: local
    driver_opts:
      type: none
      device: /home/antoda-s/data/wp
      o: bind