
services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    image: mariadb:42
    expose:
      - "3306"
    env_file:
      - ../.env
    restart: always
    networks:
      - inception
    volumes:
      - dbvol:/var/lib/mysql
    secrets:
      - db_host
      - db_name
      - db_password
      - db_root_password
      - wp_admin_password
      - wp_user_password

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress:42
    expose:
      - "9000"
    depends_on:
      - mariadb
    env_file:
      - ../.env
    restart: on-failure
    networks:
      - inception
    volumes:
      - wpvol:/var/www/html/wordpress
    secrets:
      - db_host
      - db_name
      - db_password
      - db_root_password
      - wp_admin_password
      - wp_user_password
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    image: nginx:42
    ports:
      - "443:443"
    depends_on:
      - wordpress
    env_file:
      - ../.env
    restart: on-failure
    networks:
      - inception
    volumes:
      - wpvol:/var/www/html/wordpress

secrets:
  db_host:
    file: ../secrets/db_host.txt
  db_name:
    file: ../secrets/db_name.txt
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt

networks:
  inception:
    name: inception
    driver: bridge

volumes: 
  dbvol:
    name: dbvol
    driver: local
    driver_opts:
      type: none
      device: /home/antoda-s/data/db
      o: bind
  wpvol:
    name: wpvol
    driver: local
    driver_opts:
      type: none
      device: /home/antoda-s/data/wp
      o: bind